- name: script execution
  hosts: all
  become: yes 
  tasks:

    - name: CP to RH 
      ansible.builtin.copy:
        src: /home/kub/ans/download.sh
        dest: /tmp/download.sh
        mode: '0755'

    - name: execute 
      ansible.builtin.stat:
        path: "/tmp/skr/download.sh"
      register: script_info

    - name: execute
      ansible.builtin.shell: ./download.sh
      args:
        chdir: /tmp
